
// Uma lista de recomendacoes para aparecer na caixa de pesquisa, a gente tirou do banco de dados
const lista = [ 'peixe agua salgada salmao file c/ pele fresco grelhado s/ oleo',
  'bebida cha infusao colonia planta folha s/ acucar',
  'carne boi peito s/ gordura grelhada s/ sal',
  'milho verde grao assado s/ sal',
  'pequi polpa cozido s/ oleo s/ sal',
  'peixe agua doce lambari fresco cozido s/ oleo s/ sal',
  'carne frango coracao cozida (liquido do cozimento excluido) s/ oleo s/ sal',
  'bebida cha preto infusao ',
  'carne boi miolo de alcatra s/ gordura grelhada s/ oleo s/ sal',
  'cenoura s/ casca cozida drenada s/ oleo s/ sal',
  'batata doce s/ casca cozida drenada s/ oleo s/ sal',
  'bebida cafe infusao   medio',
  'linguica frango/porco fresca grelhada/assada s/ oleo',
  'milho verde grao assado c/ sal',
  'pimentao vermelho cozido drenado s/ oleo s/ sal',
  'acelga cozida drenada s/ oleo',
  'carne frango inteiro s/ pele frita (c/ oleo de soja) s/ sal',
  'suco natural carambola',
  'peixe sardinha file microondas/ min s/ oleo s/ sal',
  'cogumelo shiimeji cozido s/ oleo s/ sal',
  'rabanete c/ casca cozido drenado s/ oleo s/ sal',
  'peixe agua salgada porquinho assado/grelhado s/ oleo s/ sal',
  'milho pipoca s/ sal',
  'peixe agua salgada tainha file cozido/ min s/ oleo s/ sal',
  'carne boi musculo s/ gordura cozida s/ oleo s/ sal',
  'batata inglesa s/ casca assada s/ oleo s/ sal',
  'bebida cafe infusao   suave',
  'molusco ostra cozido s/ oleo s/ sal',
  'tomate maduro cozido s/ oleo',
  'carne peru peito s/ pele frita (c/ oleo de soja) s/ sal',
  'carne caca (capivara coelho) cozida assada s/ oleo',
  'pimentao amarelo assado s/ oleo s/ sal',
  'soja grao seco em estufa',
  'jilo c/ casca frito (c/ oleo de soja) s/ sal',
  'ovo galinha inteiro cozido',
  'chuchu s/ casca cozido drenado s/ oleo s/ sal',
  'flor de abobora cozida drenada s/ oleo',
  'carne porco pernil frita (c/ oleo de soja) s/ sal',
  'carne frango asa c/ pele cozida (liquido do cozimento excluido) s/ oleo s/ sal',
  'macarrao trigo seco cozido drenado',
  'abobora moranga s/ casca s/ semente cozida drenada s/ oleo',
  'peixe agua salgada pescada branca assado/grelhado s/ oleo s/ sal',
  'cebolinha verde cozida s/ oleo s/ sal',
  'molusco polvo cozido s/ oleo',
  'peixe agua salgada sardinha frita s/ sal',
  'cebola branca assada s/ oleo s/ sal',
  'arroz integral cozido s/ sal e oleo',
  'pimentao verde cozido drenado s/ oleo sal',
  'feijao carioca cozido ( grao e  caldo) s/ oleo s/ sal',
  'pimentao vermelho assado s/ oleo s/ sal',
  'suco natural bacuri',
  'carne porco pernil assada s/ oleo s/ sal',
  'carne porco preparada s/ sal (media de diferentes cortes e preparos)',
  'carne cabrito cozida assada s/ oleo',
  'carne boi fraldinha c/ gordura frita (c/ oleo de soja) s/ sal',
  'carne frango peito s/ pele assada s/ oleo s/ sal',
  'arroz polido cozido s/ sal e oleo (media diferentes cultivares)',
  'carne bovina quarto dianteiro s/ gordura cozida s/ oleo s/ sal',
  'berinjela cozida drenada s/ oleo s/ sal',
  'peixe agua salgada abadejo file congelado assado s/ oleo s/ sal',
  'couve cozida drenada s/ oleo s/ sal',
  'carne boi file mignon s/ gordura frita (c/ oleo de soja) s/ sal',
  'carne boi acem s/ gordura cozida s/ oleo s/ sal',
  'carne boi lagarto frita (c/ oleo de soja) s/ sal',
  'cogumelo paris cozido drenado s/ oleo c/ sal',
  'carne boi flanco s/ gordura cozida s/ sal',
  'carne frango caipira inteiro c/ pele cozida s/ oleo s/ sal',
  'alhoporo cozido drenado s/ oleo s/ sal',
  'carne boi rabo cozido s/ oleo',
  'carne frango figado frita (c/ oleo de soja)',
  'peixe agua doce corvina cozido s/ oleo s/ sal',
  'peixe agua doce corimbata cozido / oleo s/ sal',
  'carne vitela cozida s/oleo',
  'inhame s/ casca cozido drenado s/ oleo s/ sal',
  'peixe agua doce pintado grelhado s/ oleo s/ sal',
  'carne cabrito assada s/ oleo s/ sal (media de diferentes cortes e racas)',
  'lentilha cozida drenada s/ oleo s/ sal',
  'camarao pitu frito s/ sal',
  'bebida infusao malvasanta planta folha s/ acucar',
  'cheiroverde ( cebolinha verde  salsa) cozido s/ oleo',
  'carne frango coxa s/ pele cozida s/ oleo s/ sal',
  'carne ovino ovelha perna cozida assada s/ oleo',
  'ovo galinha inteiro frito (c/ oleo de soja)',
  'batata baroa (mandioquinha batata salsa) s/ casca cozida drenada s/ oleo s/ sal',
  'repolho branco cozido drenado s/ oleo s/ sal',
  'carne boi contrafile grelhado/frito s/ sal',
  'peixe agua doce lambari congelado frito s/ sal',
  'salsa cozida drenada s/ oleo s/ sal',
  'peixe agua doce corimbata assado s/ oleo s/ sal',
  'peixe agua salgada abadejo file congelado cozido s/ oleo',
  'carne boi seca cozida s/ oleo',
  'peixe sticks congelado',
  'bebida infusao hortela rasteira planta folha s/ acucar',
  'batata doce s/ casca frita (c/ oleo de soja)',
  'carne boi picanha s/ gordura grelhada s/ sal',
  'peixe agua doce pintado cozido s/ oleo s/ sal',
  'carne frango coracao grelhada s/ oleo c/ sal',
  'molusco mexilhao cozido s/ oleo s/ sal',
  'taioba folha cozida drenada s/ oleo s/ sal']; 



let tam = lista.length;
// a medida que o usuario vai digitando algo na caixa de texto ele ja vai recomendando os alimentos que estao na lista acima
function show(value){
  document.getElementById("datalist").innerHTML = "";
  var i;
  for(i = 0; i<tam; i++){
    if(lista[i].indexOf(value.toLowerCase())>-1){
      var n = document.createElement("option");
      var v = document.createTextNode(lista[i]);
      n.appendChild(v);
      document.getElementById("datalist").appendChild(n);
    }

  }
}

